#coding:utf-8
import sys

from config import PisConfig

#postsql
#&Y%GTGBH*S#f5^h

STATE_READ_START_FLAG	= 0
STATE_READ_HAEHER		= 1
STATE_READ_DATA			= 2
STATE_READ_END_FLAG		= 3

START_FLAG			= 0xA5A5A5A5
END_FLAG			= 0xDEDEDEDE

START_FLAG_LEN		= 4
END_FLAG_LEN		= 4
HEADER_LEN			= 20
MIN_PKT_LEN			= HEADER_LEN + END_FLAG_LEN #24

PKT_EXTRA_LEN		= MIN_PKT_LEN

LOCAL_TCP_PORT			= 11615

LOCAL_UDP_PORT			= 11616
REMOTE_UDP_PORT			= 12880

CONN_ERROR_WAIT			= 5

MAX_PKT_LEN				= 1024 * 1024
RX_BUF_LEN				= MAX_PKT_LEN * 10

ACK_TIMEOUT				= 4
RESEND_LIMIT			= 3

REQUEST_TIMEOUT			= 20 # 20 seconds

MODBUS_SVR_PORT 		= 502
MODBUS_SVR_TICK			= 1 * 60

"""
REMOTE_UDP_PORT			= 12880
"""

PACKET_DEBUG			= PisConfig["packetDebug"]

INSTALL_TYPE_HEAD		= "0"
INSTALL_TYPE_TAIL		= "1"
INSTALL_TYPE_UP			= "2"
INSTALL_TYPE_DOWN		= "3"
INSTALL_TYPE_HALL		= "4"
INSTALL_TYPE_OTHER		= "5"

#modbus register address
#H hall
#U up
#D down
MB_ADDR_STATUS_HC		= 0x01
MB_ADDR_STATUS_UC		= 0x02
MB_ADDR_STATUS_DC		= 0x03

MB_ADDR_CTRL_HC			= 0x0B
MB_ADDR_CTRL_UC			= 0x0C
MB_ADDR_CTRL_DC			= 0x0D

MB_ADDR_MSG_SEL_ALL		= 0x15
MB_ADDR_MSG_MODE		= 0x16
MB_ADDR_MSG_CONTENT		= 0x33

MB_ADDR_D1_DEST			= 0xC9
MB_ADDR_D1_TIME_HH		= 0xCD
MB_ADDR_D1_TIME_MM		= 0xCC

MB_ADDR_D2_DEST			= 0xCF
MB_ADDR_D2_TIME_HH		= 0xD3
MB_ADDR_D2_TIME_MM		= 0xD2

MB_ADDR_U1_DEST			= 0xC8
MB_ADDR_U1_TIME_HH		= 0xCB
MB_ADDR_U1_TIME_MM		= 0xCA

MB_ADDR_U2_DEST			= 0xCE
MB_ADDR_U2_TIME_HH		= 0xD1
MB_ADDR_U2_TIME_MM		= 0xD0

USING_MSGER             = False
